rethinkdb_backup:
  build: .
  environment:
    - CRON_TIME=* * * * *
    - RETHINKDB_DB=tsab
  links:
    - rethinkdb
  # volumes_from:
    # - rethinkdb
  volumes:
    - /backup:/backup
rethinkdb:
  image: 'rethinkdb:2.2.0'
  command: 'rethinkdb --bind all'
  ports:
    - '8080:8080'
    - '28015:28015'
  restart: always
