rethinkdb_backup:
  build: .
  environment:
    - CRON_TIME=* * * * *
    - RETHINKDB_ENV=DEVELOPMENT
  links:
    - rethinkdb-dev
  volumes:
    - /backup:/backup
rethinkdb-dev:
  image: 'rethinkdb:2.2.0'
  command: 'rethinkdb --bind all'
  ports:
    - '28015:28015'
  restart: always
